#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftingProject.DatabaseAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dwk-multiple-projects")]
	public partial class DWKDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DWKDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dwk_multiple_projectsConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DWKDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<UserModel> UserModels
		{
			get
			{
				return this.GetTable<UserModel>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="org.AddUser")]
		public int AddUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SponsorName", DbType="NVarChar(50)")] string sponsorName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sponsorName, userName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="org.GetUser")]
		public ISingleResult<UserModel> GetUser([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(50)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName);
			return ((ISingleResult<UserModel>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="org.UserModel")]
	public partial class UserModel
	{
		
		private string _UserName;
		
		private System.Nullable<int> _UserSponsorCount;
		
		private System.Nullable<int> _UserOwnerCount;
		
		private string _SponsorName;
		
		private System.Nullable<int> _SponsorSponsorCount;
		
		private System.Nullable<int> _SponsorOwnerCount;
		
		private string _OwnerName;
		
		private System.Nullable<int> _OwnerSponsorCount;
		
		private System.Nullable<int> _OwnerOwnerCount;
		
		public UserModel()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserSponsorCount", DbType="Int")]
		public System.Nullable<int> UserSponsorCount
		{
			get
			{
				return this._UserSponsorCount;
			}
			set
			{
				if ((this._UserSponsorCount != value))
				{
					this._UserSponsorCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserOwnerCount", DbType="Int")]
		public System.Nullable<int> UserOwnerCount
		{
			get
			{
				return this._UserOwnerCount;
			}
			set
			{
				if ((this._UserOwnerCount != value))
				{
					this._UserOwnerCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorName", DbType="NVarChar(50)")]
		public string SponsorName
		{
			get
			{
				return this._SponsorName;
			}
			set
			{
				if ((this._SponsorName != value))
				{
					this._SponsorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorSponsorCount", DbType="Int")]
		public System.Nullable<int> SponsorSponsorCount
		{
			get
			{
				return this._SponsorSponsorCount;
			}
			set
			{
				if ((this._SponsorSponsorCount != value))
				{
					this._SponsorSponsorCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SponsorOwnerCount", DbType="Int")]
		public System.Nullable<int> SponsorOwnerCount
		{
			get
			{
				return this._SponsorOwnerCount;
			}
			set
			{
				if ((this._SponsorOwnerCount != value))
				{
					this._SponsorOwnerCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerName", DbType="NVarChar(50)")]
		public string OwnerName
		{
			get
			{
				return this._OwnerName;
			}
			set
			{
				if ((this._OwnerName != value))
				{
					this._OwnerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerSponsorCount", DbType="Int")]
		public System.Nullable<int> OwnerSponsorCount
		{
			get
			{
				return this._OwnerSponsorCount;
			}
			set
			{
				if ((this._OwnerSponsorCount != value))
				{
					this._OwnerSponsorCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerOwnerCount", DbType="Int")]
		public System.Nullable<int> OwnerOwnerCount
		{
			get
			{
				return this._OwnerOwnerCount;
			}
			set
			{
				if ((this._OwnerOwnerCount != value))
				{
					this._OwnerOwnerCount = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
