<?xml version="1.0" encoding="utf-8"?><Database Name="dwk-multiple-projects" Class="DWKDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=dwk-sql-server-01.database.windows.net;Initial Catalog=dwk-multiple-projects;User ID=TimerToysApp" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dwk_multiple_projectsConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="org.UserModel" Member="UserModels">
    <Type Name="UserModel" Id="ID1">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UserSponsorCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserOwnerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SponsorName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SponsorSponsorCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SponsorOwnerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OwnerSponsorCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OwnerOwnerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="org.AddUser" Method="AddUser">
    <Parameter Name="SponsorName" Parameter="sponsorName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="org.GetUser" Method="GetUser">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>